version: '3.8'

services:
  index-gap-finder:
    build: .
    container_name: index-gap-finder
    ports:
      - "7004:7004"
    environment:
      - ES_HOST=${ES_HOST:-http://elastic.dijidemi.com:80}
      - ES_USER=${ES_USER:-elastic}
      - ES_PASSWORD=${ES_PASSWORD:-123654-}
      - ES_INDEX=${ES_INDEX:-question_bank}
      - SQL_SERVER=${SQL_SERVER:-sql.impark.local}
      - SQL_USER=${SQL_USER:-muzaffer.yalcin}
      - SQL_PASSWORD=${SQL_PASSWORD:-Impark2025!*}
      - SQL_DATABASE=${SQL_DATABASE:-olcme_db}
      - FLASK_APP=${FLASK_APP:-app.py}
      - FLASK_ENV=${FLASK_ENV:-production}
      - APP_HOST=${APP_HOST:-0.0.0.0}
      - APP_PORT=${APP_PORT:-7004}
    extra_hosts:
      - "elastic.dijidemi.com:172.17.3.31"
      - "sql.impark.local:172.17.3.101"
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - elastic-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7004/eksik-kitaplar"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 40s

networks:
  elastic-network:
    driver: bridge 